<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Xisco Ribera &amp; Irene Julià">

<title>Clustering</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Entrega_Clustering_files/libs/clipboard/clipboard.min.js"></script>
<script src="Entrega_Clustering_files/libs/quarto-html/quarto.js"></script>
<script src="Entrega_Clustering_files/libs/quarto-html/popper.min.js"></script>
<script src="Entrega_Clustering_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Entrega_Clustering_files/libs/quarto-html/anchor.min.js"></script>
<link href="Entrega_Clustering_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Entrega_Clustering_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Entrega_Clustering_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Entrega_Clustering_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Entrega_Clustering_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#presentación-del-problema" id="toc-presentación-del-problema" class="nav-link active" data-scroll-target="#presentación-del-problema">Presentación del problema</a></li>
  <li><a href="#convertir-los-datos-en-tidy" id="toc-convertir-los-datos-en-tidy" class="nav-link" data-scroll-target="#convertir-los-datos-en-tidy">Convertir los datos en tidy</a></li>
  <li><a href="#variables" id="toc-variables" class="nav-link" data-scroll-target="#variables">Variables</a></li>
  <li><a href="#estimación-del-vector-de-medias-y-la-matriz-de-covarianza-y-correlación" id="toc-estimación-del-vector-de-medias-y-la-matriz-de-covarianza-y-correlación" class="nav-link" data-scroll-target="#estimación-del-vector-de-medias-y-la-matriz-de-covarianza-y-correlación">Estimación del vector de medias y la matriz de covarianza y correlación</a></li>
  <li><a href="#análisis-multivariante" id="toc-análisis-multivariante" class="nav-link" data-scroll-target="#análisis-multivariante">Análisis multivariante</a></li>
  <li><a href="#análisis-de-normalidad-multivariante" id="toc-análisis-de-normalidad-multivariante" class="nav-link" data-scroll-target="#análisis-de-normalidad-multivariante">Análisis de normalidad multivariante</a></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones">Conclusiones</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Clustering</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Xisco Ribera &amp; Irene Julià </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="presentación-del-problema" class="level1">
<h1>Presentación del problema</h1>
<p>Vamos a tratar una base de datos relacionados con la predicción de riesgo de cirrosis. La cirrosis es una etapa tardía de la cicatrización (fibrosis) del hígado causada por muchas formas de enfermedades y afecciones hepáticas, como la hepatitis y el alcoholismo crónico.</p>
<p>Nuestro objetivo para este estudio sería:</p>
<ol type="1">
<li>Estudiar algunos perfiles con riesgo de padecer cirrosis.</li>
</ol>
<p>Los datos provienen de la página web Kaggle: <a href="https://www.kaggle.com/datasets/fedesoriano/cirrhosis-prediction-dataset">Kaggle - Cirrhosis Prediction Dataset</a>.</p>
<p>El dataset consta de 418 muestras, donde cada una representa una serie de características de un paciente. A cada paciente se le atribuyen 20 valores, uno de ellos es su ID, y el resto son variables relacionadas con la salud.</p>
<p>Antes de explicar cada variable, modifiquemos la tabla de datos para tenerla limpia en formato tidy.</p>
<p>Cargamos la librerías que utilizaremos</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fmsb)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mvnormtest)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nortest)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fBasics)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="convertir-los-datos-en-tidy" class="level1">
<h1>Convertir los datos en tidy</h1>
<p>Cargamos la tabla de datos y la convertimos a tibble para facilitarnos la manipulación.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"cirrhosis.csv"</span>, <span class="at">header =</span> T)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">=</span> datos <span class="sc">%&gt;%</span> as.tibble</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(datos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 418
Columns: 20
$ ID            &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1…
$ N_Days        &lt;int&gt; 400, 4500, 1012, 1925, 1504, 2503, 1832, 2466, 2400, 51,…
$ Status        &lt;chr&gt; "D", "C", "D", "D", "CL", "D", "C", "D", "D", "D", "D", …
$ Drug          &lt;chr&gt; "D-penicillamine", "D-penicillamine", "D-penicillamine",…
$ Age           &lt;int&gt; 21464, 20617, 25594, 19994, 13918, 24201, 20284, 19379, …
$ Sex           &lt;chr&gt; "F", "F", "M", "F", "F", "F", "F", "F", "F", "F", "F", "…
$ Ascites       &lt;chr&gt; "Y", "N", "N", "N", "N", "N", "N", "N", "N", "Y", "N", "…
$ Hepatomegaly  &lt;chr&gt; "Y", "Y", "N", "Y", "Y", "Y", "Y", "N", "N", "N", "Y", "…
$ Spiders       &lt;chr&gt; "Y", "Y", "N", "Y", "Y", "N", "N", "N", "Y", "Y", "Y", "…
$ Edema         &lt;chr&gt; "Y", "N", "S", "S", "N", "N", "N", "N", "N", "Y", "N", "…
$ Bilirubin     &lt;dbl&gt; 14.5, 1.1, 1.4, 1.8, 3.4, 0.8, 1.0, 0.3, 3.2, 12.6, 1.4,…
$ Cholesterol   &lt;int&gt; 261, 302, 176, 244, 279, 248, 322, 280, 562, 200, 259, 2…
$ Albumin       &lt;dbl&gt; 2.60, 4.14, 3.48, 2.54, 3.53, 3.98, 4.09, 4.00, 3.08, 2.…
$ Copper        &lt;int&gt; 156, 54, 210, 64, 143, 50, 52, 52, 79, 140, 46, 94, 40, …
$ Alk_Phos      &lt;dbl&gt; 1718.0, 7394.8, 516.0, 6121.8, 671.0, 944.0, 824.0, 4651…
$ SGOT          &lt;dbl&gt; 137.95, 113.52, 96.10, 60.63, 113.15, 93.00, 60.45, 28.3…
$ Tryglicerides &lt;int&gt; 172, 88, 55, 92, 72, 63, 213, 189, 88, 143, 79, 95, 130,…
$ Platelets     &lt;int&gt; 190, 221, 151, 183, 136, NA, 204, 373, 251, 302, 258, 71…
$ Prothrombin   &lt;dbl&gt; 12.2, 10.6, 12.0, 10.3, 10.9, 11.0, 9.7, 11.0, 11.0, 11.…
$ Stage         &lt;int&gt; 4, 3, 4, 4, 3, 3, 3, 3, 2, 4, 4, 4, 3, 4, 3, 3, 4, 4, 3,…</code></pre>
</div>
</div>
<p>Vamos a modificar el data set para que sea más cómodo a la hora de trabajar con él.</p>
<p>Transformamos las variables qualitativas en factor y, en las de Si o No (Y: Si, N: No) cambiamos los valores para que sea más ilustrativa y entendible. De la misma forma con el sexo cromosómico (F: Female, M: Male)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">=</span> datos <span class="sc">%&gt;%</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Status =</span> <span class="fu">factor</span>(Status, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"C"</span>, <span class="st">"CL"</span>, <span class="st">"D"</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Cens"</span>, </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>                                                      <span class="st">"Cens_Trat"</span>, <span class="st">"Muerto"</span>)))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">=</span> datos <span class="sc">%&gt;%</span> </span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Drug =</span> Drug <span class="sc">%&gt;%</span> as.factor)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">=</span> datos <span class="sc">%&gt;%</span> </span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Sex =</span> <span class="fu">if_else</span>(Sex <span class="sc">==</span> <span class="st">"F"</span>, <span class="st">"Female"</span>, <span class="st">"Male"</span>) <span class="sc">%&gt;%</span> as.factor)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">=</span> datos <span class="sc">%&gt;%</span> </span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Ascites =</span> <span class="fu">if_else</span>(Ascites <span class="sc">==</span> <span class="st">"Y"</span>, <span class="st">"Si"</span>, <span class="st">"No"</span>) <span class="sc">%&gt;%</span> as.factor)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">=</span> datos <span class="sc">%&gt;%</span> </span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Hepatomegaly =</span> <span class="fu">if_else</span>(Hepatomegaly <span class="sc">==</span> <span class="st">"Y"</span>, <span class="st">"Si"</span>, <span class="st">"No"</span>) <span class="sc">%&gt;%</span> as.factor)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">=</span> datos <span class="sc">%&gt;%</span> </span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Spiders =</span> <span class="fu">if_else</span>(Spiders <span class="sc">==</span> <span class="st">"Y"</span>, <span class="st">"Si"</span>, <span class="st">"No"</span>) <span class="sc">%&gt;%</span> as.factor)</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">=</span> datos <span class="sc">%&gt;%</span> </span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Edema =</span> <span class="fu">factor</span>(Edema, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Y"</span>, <span class="st">"N"</span>, <span class="st">"S"</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Si"</span>, <span class="st">"No"</span>,</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>                                                                     <span class="st">"Sin"</span>)))</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">=</span> datos <span class="sc">%&gt;%</span> </span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Stage =</span> Stage <span class="sc">%&gt;%</span> as.factor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Observemos que hay muestras que tienen valores desconocidos (NA). Veamos cuales son:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 142 × 20
      ID N_Days Status Drug         Age Sex   Ascites Hepatomegaly Spiders Edema
   &lt;int&gt;  &lt;int&gt; &lt;fct&gt;  &lt;fct&gt;      &lt;int&gt; &lt;fct&gt; &lt;fct&gt;   &lt;fct&gt;        &lt;fct&gt;   &lt;fct&gt;
 1     6   2503 Muerto Placebo    24201 Fema… No      Si           No      No   
 2    14   1217 Muerto Placebo    20535 Male  Si      Si           No      Si   
 3    40   4467 Cens   D-penicil… 17046 Fema… No      No           No      No   
 4    41   1350 Muerto D-penicil… 12285 Fema… No      Si           No      No   
 5    42   4453 Cens   Placebo    12307 Fema… No      Si           Si      No   
 6    45   4025 Cens   Placebo    15265 Fema… No      No           No      No   
 7    49    708 Muerto Placebo    22336 Fema… No      Si           No      No   
 8    53   1000 Muerto D-penicil… 24621 Fema… No      Si           No      No   
 9    58   4459 Cens   D-penicil… 16279 Male  No      No           No      No   
10    70   3458 Cens   D-penicil… 20600 Fema… No      No           No      No   
# ℹ 132 more rows
# ℹ 10 more variables: Bilirubin &lt;dbl&gt;, Cholesterol &lt;int&gt;, Albumin &lt;dbl&gt;,
#   Copper &lt;int&gt;, Alk_Phos &lt;dbl&gt;, SGOT &lt;dbl&gt;, Tryglicerides &lt;int&gt;,
#   Platelets &lt;int&gt;, Prothrombin &lt;dbl&gt;, Stage &lt;fct&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">=</span> <span class="fu">na.omit</span>(datos)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>datos</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 276 × 20
      ID N_Days Status    Drug      Age Sex   Ascites Hepatomegaly Spiders Edema
   &lt;int&gt;  &lt;int&gt; &lt;fct&gt;     &lt;fct&gt;   &lt;int&gt; &lt;fct&gt; &lt;fct&gt;   &lt;fct&gt;        &lt;fct&gt;   &lt;fct&gt;
 1     1    400 Muerto    D-peni… 21464 Fema… Si      Si           Si      Si   
 2     2   4500 Cens      D-peni… 20617 Fema… No      Si           Si      No   
 3     3   1012 Muerto    D-peni… 25594 Male  No      No           No      Sin  
 4     4   1925 Muerto    D-peni… 19994 Fema… No      Si           Si      Sin  
 5     5   1504 Cens_Trat Placebo 13918 Fema… No      Si           Si      No   
 6     7   1832 Cens      Placebo 20284 Fema… No      Si           No      No   
 7     8   2466 Muerto    Placebo 19379 Fema… No      No           No      No   
 8     9   2400 Muerto    D-peni… 15526 Fema… No      No           Si      No   
 9    10     51 Muerto    Placebo 25772 Fema… Si      No           Si      Si   
10    11   3762 Muerto    Placebo 19619 Fema… No      Si           Si      No   
# ℹ 266 more rows
# ℹ 10 more variables: Bilirubin &lt;dbl&gt;, Cholesterol &lt;int&gt;, Albumin &lt;dbl&gt;,
#   Copper &lt;int&gt;, Alk_Phos &lt;dbl&gt;, SGOT &lt;dbl&gt;, Tryglicerides &lt;int&gt;,
#   Platelets &lt;int&gt;, Prothrombin &lt;dbl&gt;, Stage &lt;fct&gt;</code></pre>
</div>
</div>
<p>Ascites Hepatomegaly Spiders Edema Stage</p>
<p>Guardamos el dataset:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># write.table(datos, "cirrosis_tidy.csv")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Cargamos los datos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#datos &lt;- read_csv("cirrosis_tidy.csv",</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co">#                  cols(Ascites = col_factor(),</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a> <span class="co">#                      Hepatomegaly = col_factor(),</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#                     Spiders = col_factor(),</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>   <span class="co">#                    Edema = col_factor(),</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="co">#                   Stage = col_factor()))</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co">#glimpse(datos)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>El tibble resultante consta de 276 observaciones y 20 variables. Cada muestra representa un paciente al que se le ha extraido la siguiente información:</p>
<ul>
<li><code>ID</code>: Identificador único</li>
<li><code>N_Days</code>: Número de días entre el registro y la fecha de defunción, transplante o estudio analítico enJulio de 1986.</li>
<li><code>Status</code>: Estatus del paciente: C (Censurado), CL (censurado debido a tratamiento hepático), o D (Muerto)</li>
<li><code>Drug</code>: Tipo de fármaco: D-penicilamina o placebo</li>
<li><code>Age</code>: Edad [días]</li>
<li><code>Sex</code>: Sexo cromosómico: Male (hombre) o Female (Mujer)</li>
<li><code>Ascites</code>: Presencia de Ascitis No o Si</li>
<li><code>Hepatomegaly</code>: Presencia de Hepatomegalia No o Si</li>
<li><code>Spiders</code>: Presencia de arañas vasculares No o Si</li>
<li><code>Edema</code>: Presencia de Edema: No (no hay edema y sin tratamiento diurético para el edema), Sin (presencia de edema sin diuréticos, o edema curado con diuréticos), o Si (edema a pesar del tratamiento con diuréticos)</li>
<li><code>Bilirubin</code>: Bilirrubina sérica [mg/dl]</li>
<li><code>Cholesterol</code>: Colesterol sérico [mg/dl]</li>
<li><code>Albumin</code>: Albúmina [g/dl]</li>
<li><code>Copper</code>: Cobre en orina [ug/day]</li>
<li><code>Alk_Phos</code>: Fosfatasa alcalina [U/liter]</li>
<li><code>SGOT</code>: SGOT [U/ml]</li>
<li><code>Triglycerides</code>: Triglicéridos [mg/dl]</li>
<li><code>Platelets</code>: Plaquetas por cúbico [ml/1000]</li>
<li><code>Prothrombin</code>: Tiempo de Protrombina [s]</li>
<li><code>Stage</code>: Estado histórico de la enfermedad (1, 2, 3, or 4)</li>
</ul>
</section>
<section id="variables" class="level1">
<h1>Variables</h1>
<p>Vamos a crear una tabla con la información de cada variable.</p>
<p>Empezamos por las cuantitativas</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>               Unidad     Media     Desv  Minimo   Maximo    Rango
N_Days           Días  1979.167 1112.380   41.00  4556.00  4515.00
Age              Días 18189.326 3843.556 9598.00 28650.00 19052.00
Bilirubin       mg/dl     3.334    4.601    0.30    28.00    27.70
Cholesterol     mg/dl   371.261  234.788  120.00  1775.00  1655.00
Albumin          g/dl     3.517    0.405    1.96     4.40     2.44
Copper         ug/día   100.768   88.269    4.00   588.00   584.00
Alk_Phos          U/l  1996.612 2115.478  289.00 13862.40 13573.40
SGOT             U/ml   124.119   56.720   28.38   457.25   428.87
Tryglicerides   mg/dl   124.978   65.281   33.00   598.00   565.00
Platelets     ml/1000   261.772   93.129   62.00   563.00   501.00
Prothrombin         s    10.736    1.008    9.00    17.10     8.10</code></pre>
</div>
</div>
<p>Veamos ahora los datos cualitativos</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       Status                 Drug         Sex      Ascites  Hepatomegaly
 Cens     :147   D-penicillamine:136   Female:242   No:257   No:134      
 Cens_Trat: 18   Placebo        :140   Male  : 34   Si: 19   Si:142      
 Muerto   :111                                                           
                                                                         
 Spiders  Edema     Stage  
 No:196   Si : 17   1: 12  
 Si: 80   No :234   2: 59  
          Sin: 25   3:111  
                    4: 94  </code></pre>
</div>
</div>
</section>
<section id="estimación-del-vector-de-medias-y-la-matriz-de-covarianza-y-correlación" class="level1">
<h1>Estimación del vector de medias y la matriz de covarianza y correlación</h1>
<p>Calculemos el vector de medias para cada variable cuantitativa</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       N_Days           Age     Bilirubin   Cholesterol       Albumin 
  1979.166667  18189.326087      3.333696    371.260870      3.516812 
       Copper      Alk_Phos          SGOT Tryglicerides     Platelets 
   100.768116   1996.611594    124.119239    124.978261    261.771739 
  Prothrombin 
    10.735507 </code></pre>
</div>
</div>
<p>Veamos ahora la matriz de covarianza (a secas)</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                    N_Days           Age   Bilirubin   Cholesterol    Albumin
N_Days        1232906.6244  -610129.4094 -2194.11504  -35582.06159  180.30136
Age           -610129.4094 14719394.7270  1377.50822 -140841.57420 -371.54418
Bilirubin       -2194.1150     1377.5082    21.09318     425.12744   -0.57906
Cholesterol    -35582.0616  -140841.5742   425.12744   54925.84499   -6.37286
Albumin           180.3014     -371.5442    -0.57906      -6.37286    0.16326
Copper         -35355.3853    27932.2350   186.35673    2569.06049   -8.55871
Alk_Phos       244885.5401  -160396.6451  1345.98758   75362.37161  -95.13112
SGOT           -12011.1921   -26254.5595   110.50816    4736.62317   -4.53434
Tryglicerides  -11855.3804     6177.4853   131.58769    4182.83900   -2.88761
Platelets       16424.4004   -53372.3893   -31.76224    4194.91462    7.45960
Prothrombin      -143.5027      945.1888     1.53087      -7.87231   -0.08117
                    Copper      Alk_Phos         SGOT Tryglicerides
N_Days        -35355.38527  244885.54010 -12011.19208  -11855.38043
Age            27932.23503 -160396.64509 -26254.55950    6177.48535
Bilirubin        186.35673    1345.98758    110.50816     131.58769
Cholesterol     2569.06049   75362.37161   4736.62317    4182.83900
Albumin           -8.55871     -95.13112     -4.53434      -2.88761
Copper          7763.14188   35519.94834   1505.80848    1633.87539
Alk_Phos       35519.94834 4459032.05871  17364.40256   25121.02417
SGOT            1505.80848   17364.40256   3205.49665     497.89872
Tryglicerides   1633.87539   25121.02417    497.89872    4246.13721
Platelets       -687.81380   28904.94902   -310.26872     613.53127
Prothrombin       18.95715     186.57104      3.98546       1.64534
                 Platelets Prothrombin
N_Days         16424.40036  -143.50266
Age           -53372.38934   945.18878
Bilirubin        -31.76224     1.53087
Cholesterol     4194.91462    -7.87231
Albumin            7.45960    -0.08117
Copper          -687.81380    18.95715
Alk_Phos       28904.94902   186.57104
SGOT            -310.26872     3.98546
Tryglicerides    613.53127     1.64534
Platelets       8641.56022   -18.04443
Prothrombin      -18.04443     1.01301</code></pre>
</div>
</div>
</section>
<section id="análisis-multivariante" class="level1">
<h1>Análisis multivariante</h1>
<div class="cell" data-hash="Entrega_Clustering_cache/html/unnamed-chunk-14_11d9b0102ab39d117fb052f31f9cf30c">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(datos_quant)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Entrega_Clustering_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="Entrega_Clustering_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="análisis-de-normalidad-multivariante" class="level1">
<h1>Análisis de normalidad multivariante</h1>
<p>Con estos datos vamos a realizar nuestro estudio de normalidad multivariante.</p>
<p>Calculemos el vector de medias</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>Medias <span class="ot">=</span> <span class="fu">colMeans</span>(datos_quant)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>la matriz de covarianza:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>S <span class="ot">=</span> <span class="fu">cov</span>(datos_quant)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>y la distancia de Mahalanobis:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>d_Mahalanobis <span class="ot">=</span> <span class="fu">apply</span>(datos_quant, <span class="at">MARGIN =</span> <span class="dv">1</span>, <span class="cf">function</span>(x)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">t</span>(x <span class="sc">-</span> Medias)<span class="sc">%*%</span><span class="fu">solve</span>(S)<span class="sc">%*%</span>(x <span class="sc">-</span> Medias))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Una vez calculadas estas medidas, representemos los datos</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">qchisq</span>((<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(datos_quant) <span class="sc">-</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>) <span class="sc">/</span> <span class="fu">nrow</span>(datos_quant), <span class="at">df =</span> <span class="dv">3</span>), <span class="fu">sort</span>(d_Mahalanobis), <span class="at">xlab =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">"Cuantiles de la "</span>, chi[<span class="dv">20</span>]<span class="sc">^</span><span class="dv">2</span>)),<span class="at">ylab=</span><span class="st">"Distancias ordenadas"</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span><span class="dv">0</span>,<span class="at">b=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Entrega_Clustering_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Vamos a realizar un test de normalidad. Utilizaremos Shapiro-Wilk:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>mvnormtest<span class="sc">::</span><span class="fu">mshapiro.test</span>(<span class="fu">t</span>(datos_quant))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  Z
W = 0.83366, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Obtenemos un p-valor muy pequeño, prácticamente 0, entonces, rechazamos la hipótesis nula y concluimos que no hay normalidad multivariante, es decir, almenos una variable individual no se distribuye normalmente.</p>
<p>Veamos una por una si se distribuyen normalmente. Aplicaremos a cada variable el el test de Shapiro Wilks, siempre y cuando haya pocos datos repetidos, ya que es sensible a este hecho.</p>
<ul>
<li><code>N-days</code></li>
</ul>
<p>Observemos el qqplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(datos<span class="sc">$</span>N_Days, <span class="at">main =</span> <span class="st">"N_days"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Entrega_Clustering_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 38 30</code></pre>
</div>
</div>
<p>Observemos que en las colas encontramos muchas muestras que se salen de las bandas de confianza, por tanto es un indicador que de questa variable no siga una normal. Corroboremoslo con un test.</p>
<p>Miremos primero si hay observaciones repetidas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(datos_quant<span class="sc">$</span>N_Days)<span class="sc">-</span><span class="fu">length</span>(<span class="fu">unique</span>(datos_quant<span class="sc">$</span>N_Days))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(datos_quant<span class="sc">$</span>N_Days)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 276</code></pre>
</div>
</div>
<p>Notemos que hay datos repetidos, por realicemos unos cuantos tests de normalidad.</p>
<pre><code>- Shapiro:</code></pre>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(datos_quant<span class="sc">$</span>N_Days)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  datos_quant$N_Days
W = 0.9707, p-value = 1.985e-05</code></pre>
</div>
</div>
<p>Nos ha salido un p-value = 1.985e-05, bastante pequeño, con lo que podemos rechazar la normalidad de esta variable.</p>
<pre><code>- Anderson-Darling</code></pre>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ad.test</span>(datos_quant<span class="sc">$</span>N_Days)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Anderson-Darling normality test

data:  datos_quant$N_Days
A = 1.9897, p-value = 4.437e-05</code></pre>
</div>
</div>
<p>Nos ha salido un p-value = 4.437e-05, bastante pequeño, con lo que también podemos rechazar la normalidad de esta variable.</p>
<p>Por tanto podemos concluir que la variable <code>N_Days</code> no sigue una distribución normal.</p>
<ul>
<li><code>Age</code></li>
</ul>
<p>Observemos el qqplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(datos_quant<span class="sc">$</span>Age, <span class="at">main =</span> <span class="st">"Age"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Entrega_Clustering_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 220  82</code></pre>
</div>
</div>
<p>Observemos que en las colas encontramos algunas muestras que se salen de las bandas de confianza, por tanto a simple vista no podemos asegurar nada.</p>
<p>Miremos primero si hay observaciones repetidas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(datos_quant<span class="sc">$</span>Age)<span class="sc">-</span><span class="fu">length</span>(<span class="fu">unique</span>(datos_quant<span class="sc">$</span>Age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>Hay 1 valor que se repite, por tanto, podemos aplicar el shapiro test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(datos_quant<span class="sc">$</span>Age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  datos_quant$Age
W = 0.9907, p-value = 0.07685</code></pre>
</div>
</div>
<p>Nos ha salido un p-value = 0.07685, por tanto estamos en la zona de penumbra y no podemos concluir nada. Necesitaríamos más datos para poder asegurar o negar la normalidad.</p>
<p>Realicemos otro test de normalidad.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ad.test</span>(datos_quant<span class="sc">$</span>Age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Anderson-Darling normality test

data:  datos_quant$Age
A = 0.47535, p-value = 0.238</code></pre>
</div>
</div>
<p>Con el test de Anderson-Darling nos sale un p-value = 0.238 y con este test podríamos asegurar la normalidad, aunque nosotros cogeremos esta concluisión con pinzas.</p>
<p>Veamos la densidad de esta variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>datos_quant <span class="sc">%&gt;%</span> </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Age)) <span class="sc">+</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="dv">4</span>,</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">lwd =</span> <span class="dv">1</span>,</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">linetype =</span> <span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Entrega_Clustering_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Tiene una forma parecida a una densidad normal, pero no podríamos asegurar esta tendencia.</p>
<ul>
<li><code>Bilirubin</code></li>
</ul>
<p>Observemos el qqplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(datos_quant<span class="sc">$</span>Bilirubin, <span class="at">main =</span> <span class="st">"Bilirubin"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Entrega_Clustering_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 127 137</code></pre>
</div>
</div>
<p>Observemos que claramente no seguirá una normal debido a que no hay casi ninguna observación dentro de las bandas de confianza. Respaldemos esta afermación con un test.</p>
<p>Miremos primero si hay observaciones repetidas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(datos_quant<span class="sc">$</span>Bilirubin)<span class="sc">-</span><span class="fu">length</span>(<span class="fu">unique</span>(datos_quant<span class="sc">$</span>Bilirubin))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 194</code></pre>
</div>
</div>
<p>Hay 194 valores que se repiten, por tanto, no podemos aplicar el shapiro test. En su lugar apliquemos un test D’Agostino-Pearson:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dagoTest</span>(datos_quant<span class="sc">$</span>Bilirubin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 D'Agostino Normality Test

Test Results:
  STATISTIC:
    Chi2 | Omnibus: 184.3264
    Z3  | Skewness: 11.3328
    Z4  | Kurtosis: 7.4762
  P VALUE:
    Omnibus  Test: &lt; 2.2e-16 
    Skewness Test: &lt; 2.2e-16 
    Kurtosis Test: 7.638e-14 </code></pre>
</div>
</div>
<p>Nos ha salido un p-value &lt; 2.2e-16 en los tres tests, podemos rechazar la normalidad de esta variable, resultado que esperábamos con el qqplot.</p>
<ul>
<li><code>Cholesterol</code></li>
</ul>
<p>Observemos el qqplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(datos_quant<span class="sc">$</span>Cholesterol, <span class="at">main =</span> <span class="st">"Cholesterol"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Entrega_Clustering_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 113 214</code></pre>
</div>
</div>
<p>Observemos que en esta variable ocurre lo mismo que con la anterior (<code>Bilirubin</code>).</p>
<p>Miremos primero si hay observaciones repetidas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(datos_quant<span class="sc">$</span>Cholesterol)<span class="sc">-</span><span class="fu">length</span>(<span class="fu">unique</span>(datos_quant<span class="sc">$</span>Cholesterol))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 78</code></pre>
</div>
</div>
<p>Volvemos a tener muchos datos repetidos, por tanto aplicaremos otro test D’Agostino-Pearson:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dagoTest</span>(datos_quant<span class="sc">$</span>Cholesterol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 D'Agostino Normality Test

Test Results:
  STATISTIC:
    Chi2 | Omnibus: 222.421
    Z3  | Skewness: 12.2849
    Z4  | Kurtosis: 8.4558
  P VALUE:
    Omnibus  Test: &lt; 2.2e-16 
    Skewness Test: &lt; 2.2e-16 
    Kurtosis Test: &lt; 2.2e-16 </code></pre>
</div>
</div>
<p>Nos ha salido un p-value &lt; 2.2e-16 en los tres tests, podemos rechazar la normalidad de esta variable, resultado que volvíamos a esperábamos con el qqplot.</p>
<ul>
<li><code>Albumin</code></li>
</ul>
<p>Observemos el qqplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(datos_quant<span class="sc">$</span>Albumin, <span class="at">main =</span> <span class="st">"Albumin"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Entrega_Clustering_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 199 246</code></pre>
</div>
</div>
<p>Volvemos a observar que seguramente no seguirá una distribución normal debido a las observaciones que hay fuera de las bandas.</p>
<p>Miremos primero si hay observaciones repetidas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(datos_quant<span class="sc">$</span>Albumin)<span class="sc">-</span><span class="fu">length</span>(<span class="fu">unique</span>(datos_quant<span class="sc">$</span>Albumin))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 151</code></pre>
</div>
</div>
<p>Volvemos a tener muchos datos repetidos, por tanto aplicaremos otro test D’Agostino-Pearson:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dagoTest</span>(datos_quant<span class="sc">$</span>Albumin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 D'Agostino Normality Test

Test Results:
  STATISTIC:
    Chi2 | Omnibus: 20.7075
    Z3  | Skewness: -3.8537
    Z4  | Kurtosis: 2.4201
  P VALUE:
    Omnibus  Test: 3.187e-05 
    Skewness Test: 0.0001164 
    Kurtosis Test: 0.01552 </code></pre>
</div>
</div>
<p>En este caso, los tres p-values son menores que 0.05, por tanto rechazamos la normalidad de esta variable.</p>
<ul>
<li><code>Copper</code></li>
</ul>
<p>Observemos el qqplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(datos_quant<span class="sc">$</span>Copper, <span class="at">main =</span> <span class="st">"Copper"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Entrega_Clustering_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16 21</code></pre>
</div>
</div>
<p>Volvemos a observar que esta muestra no seguirá una distribución normal.</p>
<p>Miremos primero si hay observaciones repetidas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(datos_quant<span class="sc">$</span>Copper)<span class="sc">-</span><span class="fu">length</span>(<span class="fu">unique</span>(datos_quant<span class="sc">$</span>Copper))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 124</code></pre>
</div>
</div>
<p>Como volvemos a tener muchos datos repetidos, aplicaremos otro test D’Agostino-Pearson:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dagoTest</span>(datos_quant<span class="sc">$</span>Copper)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 D'Agostino Normality Test

Test Results:
  STATISTIC:
    Chi2 | Omnibus: 150.0913
    Z3  | Skewness: 10.0613
    Z4  | Kurtosis: 6.9901
  P VALUE:
    Omnibus  Test: &lt; 2.2e-16 
    Skewness Test: &lt; 2.2e-16 
    Kurtosis Test: 2.747e-12 </code></pre>
</div>
</div>
<p>Nos vuelven a salir un p-value bastante pequeño, con lo que volvemos a rechazar la normalidad de esta variable.</p>
<ul>
<li><code>Alk_Phos</code></li>
</ul>
<p>Observemos el qqplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(datos_quant<span class="sc">$</span>Alk_Phos, <span class="at">main =</span> <span class="st">"Alk_Phos"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Entrega_Clustering_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 48 33</code></pre>
</div>
</div>
<p>Tampoco seguirá una distribución normal.</p>
<p>Miremos primero si hay observaciones repetidas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(datos_quant<span class="sc">$</span>Alk_Phos)<span class="sc">-</span><span class="fu">length</span>(<span class="fu">unique</span>(datos_quant<span class="sc">$</span>Alk_Phos))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7</code></pre>
</div>
</div>
<p>No hay muchos datos repetido. Probemos de hacer un shapiro test:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(datos_quant<span class="sc">$</span>Alk_Phos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  datos_quant$Alk_Phos
W = 0.62114, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Nos sale un p-value &lt; 2.2e-16 por tanto rechazaríamos la normalidad de esta variable. Reforcemos esta afirmación realizando un test D’Agostino-Pearson:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dagoTest</span>(datos_quant<span class="sc">$</span>Alk_Phos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 D'Agostino Normality Test

Test Results:
  STATISTIC:
    Chi2 | Omnibus: 197.5003
    Z3  | Skewness: 11.7012
    Z4  | Kurtosis: 7.7835
  P VALUE:
    Omnibus  Test: &lt; 2.2e-16 
    Skewness Test: &lt; 2.2e-16 
    Kurtosis Test: 7.105e-15 </code></pre>
</div>
</div>
<p>Efectivamente la variable no sigue una distribución normal.</p>
<ul>
<li><code>SGOT</code></li>
</ul>
<p>Observemos el qqplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(datos_quant<span class="sc">$</span>SGOT, <span class="at">main =</span> <span class="st">"SGOT"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Entrega_Clustering_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 146 246</code></pre>
</div>
</div>
<p>Observemos que encontramos algunas observaciones fuera de las bandas de confianza, lo que indica que tampoco será normal.</p>
<p>Miremos primero si hay observaciones repetidas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(datos_quant<span class="sc">$</span>SGOT)<span class="sc">-</span><span class="fu">length</span>(<span class="fu">unique</span>(datos_quant<span class="sc">$</span>SGOT))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 110</code></pre>
</div>
</div>
<p>Como volvemos a tener muchos datos repetidos, aplicaremos otro test D’Agostino-Pearson:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dagoTest</span>(datos_quant<span class="sc">$</span>SGOT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 D'Agostino Normality Test

Test Results:
  STATISTIC:
    Chi2 | Omnibus: 95.1947
    Z3  | Skewness: 7.7563
    Z4  | Kurtosis: 5.919
  P VALUE:
    Omnibus  Test: &lt; 2.2e-16 
    Skewness Test: 8.66e-15 
    Kurtosis Test: 3.24e-09 </code></pre>
</div>
</div>
<p>Podemos concluir que esta variable tampoco sigue una distribución normal.</p>
<ul>
<li><code>Tryglicerides</code></li>
</ul>
<p>Observemos el qqplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(datos_quant<span class="sc">$</span>Tryglicerides, <span class="at">main =</span> <span class="st">"Tryglicerides"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Entrega_Clustering_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  65 164</code></pre>
</div>
</div>
<p>El resultado no es diferente a la de las otras variables. Confirmemos que no sigue una normal.</p>
<p>Miremos primero si hay observaciones repetidas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(datos_quant<span class="sc">$</span>Tryglicerides)<span class="sc">-</span><span class="fu">length</span>(<span class="fu">unique</span>(datos_quant<span class="sc">$</span>Tryglicerides))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 133</code></pre>
</div>
</div>
<p>Aplicaremos otro test D’Agostino-Pearson:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dagoTest</span>(datos_quant<span class="sc">$</span>Tryglicerides)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 D'Agostino Normality Test

Test Results:
  STATISTIC:
    Chi2 | Omnibus: 180.5642
    Z3  | Skewness: 10.6986
    Z4  | Kurtosis: 8.1304
  P VALUE:
    Omnibus  Test: &lt; 2.2e-16 
    Skewness Test: &lt; 2.2e-16 
    Kurtosis Test: 4.441e-16 </code></pre>
</div>
</div>
<p>Esta variable tampoco sigue una normal.</p>
<ul>
<li><code>Platelets</code></li>
</ul>
<p>Observemos el qqplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(datos_quant<span class="sc">$</span>Platelets, <span class="at">main =</span> <span class="st">"Platelets"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Entrega_Clustering_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 37 40</code></pre>
</div>
</div>
<p>Observemos que en este caso no podríamos asegurar la normalidad a simple vista, ya que hay algunas observaciones que si sobresalen de las bandas, pero la diferencia no es exaegrada. Veamos que dicen los tests de normalidad.</p>
<p>Miremos primero si hay observaciones repetidas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(datos_quant<span class="sc">$</span>Platelets)<span class="sc">-</span><span class="fu">length</span>(<span class="fu">unique</span>(datos_quant<span class="sc">$</span>Platelets))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 83</code></pre>
</div>
</div>
<p>Como volvemos a tener muchos datos repetidos, aplicaremos otro test D’Agostino-Pearson:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dagoTest</span>(datos_quant<span class="sc">$</span>Platelets)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 D'Agostino Normality Test

Test Results:
  STATISTIC:
    Chi2 | Omnibus: 6.4744
    Z3  | Skewness: 2.51
    Z4  | Kurtosis: 0.4174
  P VALUE:
    Omnibus  Test: 0.03927 
    Skewness Test: 0.01207 
    Kurtosis Test: 0.6764 </code></pre>
</div>
</div>
<p>Notemos que el p-value de Omnibus y Skewness se encuentran en la zona de penumbra. Por tanto, con estos dos p-values no podríamos afirmar nada.</p>
<p>En cambio el p-value de Kurtosis, es bastante grande y sí podríamos aceptar la normalidad de esta variable.</p>
<p>Veamos que conclusiones saca el test de Anderson-Darling:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ad.test</span>(datos_quant<span class="sc">$</span>Platelets)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Anderson-Darling normality test

data:  datos_quant$Platelets
A = 0.6102, p-value = 0.1116</code></pre>
</div>
</div>
<p>Nos sale un p-value = 0.1116. No es un p-value muy grande, por tanto la normalidad de esta variable se podría aceptar con cuidado.</p>
<p>Veamos la densidad de la variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>datos_quant <span class="sc">%&gt;%</span> </span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Platelets)) <span class="sc">+</span></span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="dv">4</span>,</span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">lwd =</span> <span class="dv">1</span>,</span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">linetype =</span> <span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Entrega_Clustering_files/figure-html/unnamed-chunk-56-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Notemos que no podemos asegurar la normalidad ya que respecto a la cola derecha no se observa tendencia normal.</p>
<ul>
<li><code>Prothrombin</code></li>
</ul>
<p>Observemos el qqplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(datos_quant<span class="sc">$</span>Prothrombin, <span class="at">main =</span> <span class="st">"Prothrombin"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Entrega_Clustering_files/figure-html/unnamed-chunk-57-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  94 164</code></pre>
</div>
</div>
<p>Observamos que seguramente esta variable tampoco seguirá una normal.</p>
<p>Miremos primero si hay observaciones repetidas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(datos_quant<span class="sc">$</span>Prothrombin)<span class="sc">-</span><span class="fu">length</span>(<span class="fu">unique</span>(datos_quant<span class="sc">$</span>Prothrombin))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 235</code></pre>
</div>
</div>
<p>La mayoría de observaciones se repiten. Aplicaremos otro test D’Agostino-Pearson:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dagoTest</span>(datos_quant<span class="sc">$</span>Prothrombin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 D'Agostino Normality Test

Test Results:
  STATISTIC:
    Chi2 | Omnibus: 124.1459
    Z3  | Skewness: 8.8365
    Z4  | Kurtosis: 6.7869
  P VALUE:
    Omnibus  Test: &lt; 2.2e-16 
    Skewness Test: &lt; 2.2e-16 
    Kurtosis Test: 1.145e-11 </code></pre>
</div>
</div>
<p>Notemos que los p-values son muy pequeños, por tanto no hay normalidad. No obstante, al tener casi todas las muestras repetidas entre sí, el test de normalidad podría estar sobreajustado, o simplemente que esta variable tiene poco rango.</p>
</section>
<section id="conclusiones" class="level1">
<h1>Conclusiones</h1>
<p>Conluimos que</p>
<ul>
<li><p>no hay normalidad multivariante</p></li>
<li><p>no hay normalidad univariante en ninguna variable quantitativa excepto en <code>Age</code> y <code>Platelets</code> que tienen una ligera tendencia a parecerse a una normal, aunque no hay evidencias fuertes para afirmar con seguridad que presenten un comportamiento normal.</p></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>